director_uuid: 71d36859-4f21-446f-8a02-f18d7f1263c6
disk_pools: []
name: us-2-sandbox
releases: null
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-60000

